//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SzpitalDBEntities : DbContext
    {
        public SzpitalDBEntities()
            : base("name=SzpitalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doktorzy> Doktorzies { get; set; }
        public virtual DbSet<Pacjenci> Pacjencis { get; set; }
        public virtual DbSet<Wizyty> Wizyties { get; set; }
        public virtual DbSet<Zarobki> Zarobkis { get; set; }
    }
}
